shaiksaahir/JID_4203_Language_Exchange

- GG/Frontend/src/Components/CreateProfile.js
to profile registration. (please work)
> Added MBTI personality types

- GG/Backend/src/Service/userService.js
- GG/Backend/src/controller/userController.js
- GG/Backend/src/migrations/2create-UserProfile.js
- GG/Backend/src/models/UserProfile.js
- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Services/userService.js
Added an "mbti" column to "userprofile" table. Run this in MySQL schema if it is not shown: ALTER TABLE userprofile
ADD COLUMN mbti varchar(255)
AFTER hobby;
> MBTI Backend integration

- GG/Backend/src/Service/userService.js
- GG/Backend/src/controller/userController.js
- GG/Backend/src/migrations/2create-UserProfile.js
- GG/Backend/src/models/UserProfile.js
- GG/Frontend/package-lock.json
- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Services/userService.js
> Vikranth Visibility Updates

- GG/Backend/src/Service/userService.js
- GG/Backend/src/controller/friendsController.js
- GG/Backend/src/controller/userController.js
- GG/Backend/src/migrations/2create-UserProfile.js
- GG/Backend/src/models/UserProfile.js
- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Services/userService.js
Aden and Townshend found a solution to storing date and time values in the UserProfile table.
> Fixed backend-integration for date/time 

- GG/Frontend/src/Components/CreateProfile.js
- GG/README.md
Updated the README to show recent progress and accurate numbering and naming. Still needs all updates for Sprint 1.
Changed the MBTI personality type naming convention to be more international.
> Update README  and MBTI 

- GG/Backend/src/config/connectDB.js
- GG/Backend/src/config/testDB.js
- GG/Backend/src/controller/APIController.js
- GG/Backend/src/controller/friendsController.js
- GG/Backend/src/route/api.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
- GG/Frontend/src/Services/findFriendsService.js
- GG/Frontend/src/Views/App.js
- GG/README.md
New page in the React App created where users can browse the names of the other accounts on the app; this page will be one way users can add new friends.
To implement, APIController had to be updated so database fields could be accessed directly with post.execute
> FriendSearch page implemented

- GG/Backend/src/config/testDB.js
- GG/Backend/src/controller/APIController.js
- GG/Frontend/package-lock.json
- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
- GG/Frontend/src/Services/findFriendsService.js
Major Changes to the friends filtering functionality
> Friends Filtering / Sorting

- GG/Frontend/src/Components/Videocall.css
- GG/Frontend/src/Components/Videocall.js
- README.md
Will be working on making this function in the Backend next
> Enter number of chat partners - UI

- GG/Frontend/src/Components/VideoRoom.js
- GG/Frontend/src/Components/Videocall.js
- README.md
Updated README with this as well
> Connected specifying # of chat partners to backend

- GG/Frontend/src/Components/Videocall.js
Updated the microphone selection drop-down to dynamically read the available microphone inputs and populate the list for the user selection.
> Audio Preferences - Fully Working

- GG/Frontend/src/Components/Videocall.css
- GG/Frontend/src/Components/Videocall.js
> VideoCall updates

- GG/Backend/src/controller/APIController.js
- GG/Backend/src/route/api.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
- GG/Frontend/src/Services/findFriendsService.js
1. Adding User Preferences API Endpoint: New API Endpoint: We created a new API endpoint /user-preferences to fetch user preferences from the UserProfile table. getUserPreferences Controller: Added a new function getUserPreferences in APIController to fetch preferences from the UserProfile table. Exporting the Controller: Ensured that getUserPreferences is properly exported from the APIController. API Route Setup: Added the route in initAPIRoute to handle the /user-preferences API call.
2. Client-Side: Fetching Preferences: handleGetUserPreferencesApi: Created a new function in findFriendsService.js to call the /user-preferences endpoint and fetch user preferences. Ensured Proper Export: Made sure that handleGetUserPreferencesApi is correctly exported from findFriendsService.js.
3. …
> Sorting FriendsList by ANY Preference - Bug Fixed.

- GG/Frontend/src/Components/VideoRoom.js
- GG/Frontend/src/Components/Videocall.css
- GG/Frontend/src/Components/Videocall.js
- README.md
Previous commit created unexpected bugs. This commit features a Video Call screen with a working translator method and Audio and Video preferences. It also features the most up-to-date Friend Search page
> Fixed bugs with the Video Call screen

- GG/Frontend/src/Components/VideoRoom.js
Duplicate code was creating a compiling error in our main branch
> Deleted duplicate code in Video Room

- GG/Frontend/src/Components/VideoRoom.js
Updated the agora token, id, and channel to a new agora project controlled by us.
> Updated VideoRoom.js

- GG/Backend/src/migrations/2create-UserProfile.js
- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
- GG/Frontend/src/Components/LogoutConfirmationPage.js
- GG/Frontend/src/Components/Translator.css
- GG/Frontend/src/Components/Translator.js
- README.md
- Fixed display of buttons across the project
- Centered necessary UI objects (a lot of them were justified to the left)
- Fixed UserProfile db migration issue
- Added README 2.3.0
> Polishing- fixing UI & README

- GG/Frontend/src/Components/VideoRoom.js
Added commented code while trying to update and fix the code to work on the newest iteration. Mainly error handling code in comments
> Updated VideoRoom.js with error handling

- GG/Frontend/src/Components/FriendSearch.css
Updated Friend Search UI to match the rest of the pages on the site
> Updated Friend Search UI

- GG/Frontend/src/Components/PostVideocall.js
- GG/Frontend/src/Components/Videocall.js
- GG/Frontend/src/Views/App.js
The user navigates to this page after joining a call. This page will host all of our post call features
> Added PostVideocall page

- README.md
Wanted to get this out before everyone added commits
> Added README 2.4.0

- GG/Backend/src/Service/dashboardService.js
- GG/Backend/src/controller/APIController.js
- GG/Backend/src/controller/dashBoardController.js
- GG/Backend/src/route/api.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
- GG/Frontend/src/Services/dashboardService.js
- GG/Frontend/src/Services/findFriendsService.js
- GG/Frontend/src/Utils/userData.js
Please review code and test it on your end to see if there are any issues, changed a good amount of files.
> Matchmaking System implemented

- GG/Backend/src/controller/userController.js
- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/PostVideocall.js
- GG/Frontend/src/Components/Videocall.css
- GG/Frontend/src/Components/Videocall.js
- README.md
fixes:
- removing original friends list from dashboard
- moved friends list button up under find friends in dashboard
- README updates
> Added in post call features + fixes

- GG/Frontend/src/Components/PostVideocall.js
- GG/Frontend/src/Components/VideoRoom.js
> PostVideoUpdates

- GG/Frontend/src/Components/VideoRoom.js
- README.md
> Agora Token update

- GG/Frontend/src/Components/FriendsList.css
- GG/Frontend/src/Components/FriendsList.js
- GG/Frontend/src/Components/PostVideocall.js
- GG/Frontend/src/Components/Postvideocall.css
Allowed User to add to friends list at the end of the video call
updated friendslist UI as well as video end call ui
> Video Call End - Add to Friends

- GG/Backend/src/controller/userController.js
- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/FriendSearch.js
- README.md
Only users with "Show" visibility will show up in list
> Restrict Find Friends list on user visibility

- GG/Frontend/src/Components/Dashboard.js
- GG/Frontend/src/Components/UserReport.css
- GG/Frontend/src/Components/UserReport.js
- GG/Frontend/src/Views/App.js
Created a user reports page on the dashboard
> Created a User reports page

- GG/Frontend/src/Components/PostVideocall.js
- GG/Frontend/src/Services/userService.js
User submitted rating gets assigned in backend to the selected partner in the drop-down of the End Call screen.
> Backend Integration for PostVideoCall

- GG/Frontend/src/Components/VideoRoom.js
> Update Agora token

- GG/Frontend/src/Components/VideoRoom.js
- GG/Frontend/src/Components/Videocall.js
- README.md
Replaced the previous "Select Number of Users in a call" feature
> Added a room selection feature to call + revamped README

- GG/Frontend/src/Components/Login.js
- GG/Frontend/src/Components/Login.scss
- GG/Frontend/src/Styles/global.scss
Began updating Global styles as well as Login.js page specifically
> Updated Login.js UI and Global.scss

- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
Added table to see characteristics of friends
> FriendsSearch Table

- GG/Frontend/src/Components/VideoRoom.js
Token Update for testing till 11/30/24 8:15PM
> Updated Token for Testing

- GG/Frontend/src/Components/VideoRoom.js
Updated mute and hide video to work properly.
> Updated Video Room.js

- GG/Frontend/src/Components/Dashboard.css
- GG/Frontend/src/Components/Login.js
- GG/Frontend/src/Components/Registration.js
Added a way to navigate from Registration to Login directly. Changed some sizing around in Dashboard
> More Dashboard and Login UI improvements

- GG/Frontend/src/Components/FriendSearch.css
- GG/Frontend/src/Components/FriendSearch.js
Made mostly aesthetic improvements to Friend Search to bring it in line with the rest of the app. Page still isn't super optimized
> Friend Search UI Update

- GG/Frontend/src/Components/UserReport.css
- GG/Frontend/src/Components/UserReport.js
Cleaned up the simple container to fit it within the overall aesthetic of the project
> Updated User Report UI

- GG/Frontend/src/Components/CreateProfile.js
- GG/Frontend/src/Components/FriendsList.js
- GG/Frontend/src/Components/HelpData.js
- GG/Frontend/src/Components/HelpPage.js
- GG/Frontend/src/Components/UserReport.css
- GG/Frontend/src/Components/UserReport.js
- GG/Frontend/src/Components/VideoPlayer.js
- GG/Frontend/src/Components/VideoRoom.js
- GG/Frontend/src/Components/Videocall.css
- GG/Frontend/src/Components/Videocall.js
UI Updates to Video call, The Help Page, and the Profile Page
> UI Updates

- GG/Frontend/src/Components/FriendsList.css
- GG/Frontend/src/Components/FriendsList.js
> Friends List

- GG/Frontend/src/Components/VideoRoom.css
- GG/Frontend/src/Components/VideoRoom.js
The CSS only impacts the chat box
> Updated Translation Feature

- GG/Frontend/src/Components/FriendSearch.js
- GG/Frontend/src/Components/FriendsList.js
Remove friends using the same functionality as with our local storage placeholder code. I also added a display message for trying to add a user who is already a friend.
> Remove Friend Functionality Added using backend

- GG/Frontend/src/Components/PostVideocall.js
Post Video Call now retrieves and updates the database friendslist
> Post Video Call Add Friend Backend Support
